# Generated by Django 4.1.2 on 2023-06-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_attendancerecord_afternoon_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
