# Generated by Django 4.1.2 on 2023-06-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_analysisindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_absent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AnalysisIndividual',
        ),
    ]
