# Generated by Django 4.1.2 on 2023-06-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_attendancerecord_is_absent_attendancerecord_is_late_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_halfday',
            field=models.BooleanField(default=False),
        ),
    ]
